version: '3.9'

services:
  fastapi:
    build: ./fastapi
    container_name: fastapi
    ports:
      - '8000:8000'
    environment:
      - OLLAMA_API=http://172.17.0.1:11434
    extra_hosts:
      - 'host.docker.internal:host-gateway'
